export const exercises = [

    {
        name: "Plank",
        description: "A core-strengthening exercise that involves holding the body in a straight line while resting on the forearms and toes.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=pSHjTRCQxIw",
        gender: "Both",
    },
    {
        name: "Mountain Climbers",
        description: "A cardio exercise that targets the core and legs by mimicking a climbing motion.",
        type: "Cardio",
        targetedpart: "Core",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=nmwgirgXLYM",
        gender: "Both",
    },
    {
        name: "Push-Ups",
        description: "A strength exercise that targets the chest, shoulders, and triceps.",
        type: "Strength",
        targetedpart: "Upper Body",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=_l3ySVKYVJ8",
        gender: "Both",
    },
    {
        name: "Burpees",
        description: "A full-body cardio and strength exercise that combines a squat, push-up, and jump.",
        type: "Cardio",
        targetedpart: "Full Body",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=TU8QYVW0gDU",
        gender: "Both",
    },
    {
        name: "Downward Dog",
        description: "A yoga pose that stretches the hamstrings, calves, and spine.",
        type: "Yoga",
        targetedpart: "Full Body",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=0Fx8f4xZxRk",
        gender: "Both",
    },
    {
        name: "Lunges",
        description: "A strength exercise that targets the legs and glutes.",
        type: "Strength",
        targetedpart: "Legs",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
        gender: "Both",
    },
    {
        name: "Bicycle Crunches",
        description: "A core exercise that targets the abs and obliques.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=9FGilxCbdz8",
        gender: "Both",
    },
    {
        name: "Warrior Pose",
        description: "A yoga pose that strengthens the legs and improves balance.",
        type: "Yoga",
        targetedpart: "Legs",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=8lVf3zEwO4I",
        gender: "Both",
    },
    {
        name: "Tricep Dips",
        description: "A strength exercise that targets the triceps and shoulders.",
        type: "Strength",
        targetedpart: "Arms",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=0326dy_-CzM",
        gender: "Both",
    },
    {
        name: "Cobra Stretch",
        description: "A yoga pose that stretches the spine and opens the chest.",
        type: "Yoga",
        targetedpart: "Spine",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=JDcdhTuycOI",
        gender: "Both",
    },
    {
        name: "Squats",
        description: "A strength exercise that targets the legs and glutes by mimicking a sitting motion.",
        type: "Strength",
        targetedpart: "Legs",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=aclHkVaku9U",
        gender: "Both",
    },
    {
        name: "Jumping Jacks",
        description: "A cardio exercise that involves jumping to a position with the legs spread wide and the hands touching overhead.",
        type: "Cardio",
        targetedpart: "Full Body",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
        gender: "Both",
    },
    {
        name: "Side Plank",
        description: "A core exercise that targets the obliques and improves balance.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=K1v3d8aUou8",
        gender: "Both",
    },
    {
        name: "High Knees",
        description: "A cardio exercise that involves running in place while lifting the knees high.",
        type: "Cardio",
        targetedpart: "Legs",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=8opcQdC-V-U",
        gender: "Both",
    },
    {
        name: "Bridge",
        description: "A strength exercise that targets the glutes and lower back.",
        type: "Strength",
        targetedpart: "Lower Body",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=wPM8icPu6H8",
        gender: "Both",
    },
    {
        name: "Child's Pose",
        description: "A yoga pose that stretches the back and relaxes the body.",
        type: "Yoga",
        targetedpart: "Back",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=3Lm3K-RYtK8",
        gender: "Both",
    },
    {
        name: "Leg Raises",
        description: "A core exercise that targets the lower abs.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=JB2oyawG9KI",
        gender: "Both",
    },
    {
        name: "Cat-Cow Stretch",
        description: "A yoga pose that stretches the spine and improves flexibility.",
        type: "Yoga",
        targetedpart: "Spine",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=kqnua4rHVVA",
        gender: "Both",
    },
    {
        name: "Russian Twists",
        description: "A core exercise that targets the obliques.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=wkD8rjkodUI",
        gender: "Both",
    },
    {
        name: "Superman",
        description: "A strength exercise that targets the lower back and glutes.",
        type: "Strength",
        targetedpart: "Lower Back",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=cc6UVRS7PW4",
        gender: "Both",
    },
    
    
    // The rest of the exercises follow the same pattern...
];
