export const exercises = [

    {
        name: "Plank",
        description: "A core-strengthening exercise that involves holding the body in a straight line while resting on the forearms and toes.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://i.insider.com/678f896b10c98eace913245a?width=1300&format=jpeg&auto=webp",
        video: "https://www.youtube.com/watch?v=pSHjTRCQxIw",
        gender: "Male",
    },
    {
        name: "Mountain Climbers",
        description: "A cardio exercise that targets the core and legs by mimicking a climbing motion.",
        type: "Cardio",
        targetedpart: "Core",
        image: "https://impactmagazine.ca/wp-content/uploads/2019/01/JF19/JF19-WorkoutTish-MountainClimber.jpg",
        video: "https://www.youtube.com/watch?v=nmwgirgXLYM",
        gender: "Female",
    },
    {
        name: "Push-Ups",
        description: "A strength exercise that targets the chest, shoulders, and triceps.",
        type: "Strength",
        targetedpart: "Upper-Body",
        image: "https://cdn.shopify.com/s/files/1/0252/3155/6686/files/Push-ups.jpg?v=1726158512",
        video: "https://www.youtube.com/watch?v=_l3ySVKYVJ8",
        gender: "Male",
    },
    {
        name: "Burpees",
        description: "A full-body cardio and strength exercise that combines a squat, push-up, and jump.",
        type: "Cardio",
        targetedpart: "Full-Body",
        image: "https://images.unsplash.com/photo-1574680178050-55c6a6a96e0a?auto=format&fit=crop&q=80&w=800&h=600",
        video: "https://www.youtube.com/watch?v=TU8QYVW0gDU",
        gender: "Male",
    },
    {
        name: "Downward Dog",
        description: "A yoga pose that stretches the hamstrings, calves, and spine.",
        type: "Yoga",
        targetedpart: "Full-Body",
        image: "https://wearethecity.com/wp-content/uploads/2024/04/Downward-Facing-Dog-yoga.jpg",
        video: "https://www.youtube.com/watch?v=w4iKQc2ebKw",
        gender: "Female",
    },
    {
        name: "Lunges",
        description: "A strength exercise that targets the legs and glutes.",
        type: "Strength",
        targetedpart: "Legs",
        image: "https://cdn.shopify.com/s/files/1/0252/3155/6686/files/Split_Squat_vs_Lunge_Differences_in_Performance.jpg?v=1718809446",
        video: "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
        gender: "Both",
    },
    {
        name: "Bicycle Crunches",
        description: "A core exercise that targets the abs and obliques.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://mcdn.coolmate.me/image/January2024/body-weight-19.jpg",
        video: "https://www.youtube.com/watch?v=9FGilxCbdz8",
        gender: "Both",
    },
    {
        name: "Warrior Pose",
        description: "A yoga pose that strengthens the legs and improves balance.",
        type: "Yoga",
        targetedpart: "Legs",
        image: "https://thumbs.dreamstime.com/b/pretty-young-female-athlete-black-sports-outfit-doing-lunge-exercise-standing-yoga-low-warrior-pose-mat-pretty-100510761.jpg",
        video: "https://www.youtube.com/watch?v=NytDpa2r34g",
        gender: "Both",
    },
    {
        name: "Tricep Dips",
        description: "A strength exercise that targets the triceps and shoulders.",
        type: "Strength",
        targetedpart: "Arms",
        image: "https://www.oldschoollabs.com/wp-content/uploads/2020/08/Doing-Dips-for-the-First-Time2.jpg",
        video: "https://www.youtube.com/watch?v=0326dy_-CzM",
        gender: "Both",
    },
    {
        name: "Cobra Stretch",
        description: "A yoga pose that stretches the spine and opens the chest.",
        type: "Yoga",
        targetedpart: "Spine",
        image: "https://s36370.pcdn.co/wp-content/uploads/2016/09/Upward-Dog-Pose.jpg",
        video: "https://www.youtube.com/watch?v=JDcdhTuycOI",
        gender: "Both",
    },
    {
        name: "Squats",
        description: "A strength exercise that targets the legs and glutes by mimicking a sitting motion.",
        type: "Strength",
        targetedpart: "Legs",
        image: "https://www.oldschoollabs.com/wp-content/uploads/2020/02/6-Master-the-Squat-in-5-Easy-Steps2-1.jpg",
        video: "https://www.youtube.com/watch?v=aclHkVaku9U",
        gender: "Both",
    },
    {
        name: "Jumping Jacks",
        description: "A cardio exercise that involves jumping to a position with the legs spread wide and the hands touching overhead.",
        type: "Cardio",
        targetedpart: "Full-Body",
        image: "https://www.oldschoollabs.com/wp-content/uploads/2020/07/Jumping-Jacks.jpg",
        video: "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
        gender: "Both",
    },
    {
        name: "Side Plank",
        description: "A core exercise that targets the obliques and improves balance.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://nirvana-store-assets.s3.ap-southeast-1.amazonaws.com/4_3a2aee5160.png",
        video: "https://www.youtube.com/watch?v=NXr4Fw8q60o",
        gender: "Both",
    },
    {
        name: "High Knees",
        description: "A cardio exercise that involves running in place while lifting the knees high.",
        type: "Cardio",
        targetedpart: "Legs",
        image: "https://www.olyrun.com/wp-content/uploads/Why-should-you-do-high-knees-800x600.jpg",
        video: "https://www.youtube.com/watch?v=ymdS7tM0zws",
        gender: "Both",
    },
    {
        name: "Bridge",
        description: "A strength exercise that targets the glutes and lower back.",
        type: "Strength",
        targetedpart: "Lower-Body",
        image: "https://purnayoga828.com/wp-content/uploads/2015/02/SetuBandhaSarvangasana.jpg",
        video: "https://www.youtube.com/watch?v=wPM8icPu6H8",
        gender: "Both",
    },
    {
        name: "Child's Pose",
        description: "A yoga pose that stretches the back and relaxes the body.",
        type: "Yoga",
        targetedpart: "Back",
        image: "https://yogarove.com/wp-content/uploads/2020/02/sore-muscles-childs-pose.jpg",
        video: "https://www.youtube.com/watch?v=qYvYsFrTI0U",
        gender: "Both",
    },
    {
        name: "Leg Raises",
        description: "A core exercise that targets the lower abs.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://www.oldschoollabs.com/wp-content/uploads/2020/11/How-to-do-Hanging-Leg-Raises-Proper-Form3.jpg",
        video: "https://www.youtube.com/watch?v=JB2oyawG9KI",
        gender: "Both",
    },
    {
        name: "Cat-Cow Stretch",
        description: "A yoga pose that stretches the spine and improves flexibility.",
        type: "Yoga",
        targetedpart: "Spine",
        image: "https://www.yogabeyondthestudio.com/blog/wp-content/uploads/2019/04/Cow-Pose.jpg",
        video: "https://www.youtube.com/watch?v=kqnua4rHVVA",
        gender: "Both",
    },
    {
        name: "Russian Twists",
        description: "A core exercise that targets the obliques.",
        type: "Strength",
        targetedpart: "Core",
        image: "https://i.insider.com/6387756bc989f000184bfec3?width=800&format=jpeg&auto=webp",
        video: "https://www.youtube.com/watch?v=wkD8rjkodUI",
        gender: "Both",
    },
    {
        name: "Superman",
        description: "A strength exercise that targets the lower back and glutes.",
        type: "Strength",
        targetedpart: "Lower-Back",
        image: "https://bellabeat.com/wp-content/uploads/2022/02/Superman-exercise-Bellabeat-Coach.jpg",
        video: "https://www.youtube.com/watch?v=cc6UVRS7PW4",
        gender: "Female",
    },
    
    
    // The rest of the exercises follow the same pattern...
];
